name: market-analysis
services:
- name: web
  environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: owner/market-analysis
  build_command: pip install -r requirements.txt
  run_command: gunicorn --workers 4 --timeout 120 wsgi:app
  envs:
  - key: FLASK_ENV
    scope: RUN_TIME
    value: production
  - key: FLASK_APP
    scope: RUN_TIME
    value: app.py
  - key: PYTHONUNBUFFERED
    scope: RUN_TIME
    value: "1"
  instance_count: 1
  instance_size_slug: basic-xs
  http_port: 8000
  health_check:
    http_path: /health
    initial_delay_seconds: 30
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3 