name: market-analysis
services:
- name: web
  github:
    branch: main
    deploy_on_push: true
    repo: owner/market-analysis  # You'll replace this with your GitHub repo
  build_command: pip install -r requirements.txt
  run_command: gunicorn --config gunicorn_config.py wsgi:app
  envs:
  - key: FLASK_ENV
    value: production
  - key: FLASK_APP
    value: app.py
  instance_count: 1
  instance_size_slug: basic-xs
  http_port: 8000
  routes:
  - path: /
  health_check:
    http_path: /
    port: 8000 